name: test
on: [ pull_request ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - run: docker build -t test .
      - run: docker run --rm -t -e REVIEWDOG_GITHUB_API_TOKEN -e CI_REPO_OWNER -e CI_REPO_NAME -e CI_COMMIT test
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{secrets.GITHUB_TOKEN}}
          CI_REPO_OWNER: massongit
          CI_REPO_NAME: action-rubocop
          CI_COMMIT: ${{ github.event.pull_request.head.sha || github.sha }}
